/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProbabilitiesRouteImport } from './routes/probabilities'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSubmissionsRouteImport } from './routes/api/public/submissions'
import { Route as ApiPublicDebugInsertRouteImport } from './routes/api/public/debug-insert'
import { Route as ApiPublicDebugRouteImport } from './routes/api/public/debug'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbabilitiesRoute = ProbabilitiesRouteImport.update({
  id: '/probabilities',
  path: '/probabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmissionsRoute = ApiPublicSubmissionsRouteImport.update({
  id: '/api/public/submissions',
  path: '/api/public/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugInsertRoute = ApiPublicDebugInsertRouteImport.update({
  id: '/api/public/debug-insert',
  path: '/api/public/debug-insert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugRoute = ApiPublicDebugRouteImport.update({
  id: '/api/public/debug',
  path: '/api/public/debug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/moderation': typeof ModerationRoute
  '/probabilities': typeof ProbabilitiesRoute
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/api/public/debug': typeof ApiPublicDebugRoute
  '/api/public/debug-insert': typeof ApiPublicDebugInsertRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/moderation': typeof ModerationRoute
  '/probabilities': typeof ProbabilitiesRoute
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/api/public/debug': typeof ApiPublicDebugRoute
  '/api/public/debug-insert': typeof ApiPublicDebugInsertRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/moderation': typeof ModerationRoute
  '/probabilities': typeof ProbabilitiesRoute
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/api/public/debug': typeof ApiPublicDebugRoute
  '/api/public/debug-insert': typeof ApiPublicDebugInsertRoute
  '/api/public/submissions': typeof ApiPublicSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/history'
    | '/moderation'
    | '/probabilities'
    | '/profile'
    | '/stream'
    | '/trash'
    | '/users'
    | '/api/public/debug'
    | '/api/public/debug-insert'
    | '/api/public/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/history'
    | '/moderation'
    | '/probabilities'
    | '/profile'
    | '/stream'
    | '/trash'
    | '/users'
    | '/api/public/debug'
    | '/api/public/debug-insert'
    | '/api/public/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/history'
    | '/moderation'
    | '/probabilities'
    | '/profile'
    | '/stream'
    | '/trash'
    | '/users'
    | '/api/public/debug'
    | '/api/public/debug-insert'
    | '/api/public/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ModerationRoute: typeof ModerationRoute
  ProbabilitiesRoute: typeof ProbabilitiesRoute
  ProfileRoute: typeof ProfileRoute
  StreamRoute: typeof StreamRoute
  TrashRoute: typeof TrashRoute
  UsersRoute: typeof UsersRoute
  ApiPublicDebugRoute: typeof ApiPublicDebugRoute
  ApiPublicDebugInsertRoute: typeof ApiPublicDebugInsertRoute
  ApiPublicSubmissionsRoute: typeof ApiPublicSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probabilities': {
      id: '/probabilities'
      path: '/probabilities'
      fullPath: '/probabilities'
      preLoaderRoute: typeof ProbabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions': {
      id: '/api/public/submissions'
      path: '/api/public/submissions'
      fullPath: '/api/public/submissions'
      preLoaderRoute: typeof ApiPublicSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-insert': {
      id: '/api/public/debug-insert'
      path: '/api/public/debug-insert'
      fullPath: '/api/public/debug-insert'
      preLoaderRoute: typeof ApiPublicDebugInsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug': {
      id: '/api/public/debug'
      path: '/api/public/debug'
      fullPath: '/api/public/debug'
      preLoaderRoute: typeof ApiPublicDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ModerationRoute: ModerationRoute,
  ProbabilitiesRoute: ProbabilitiesRoute,
  ProfileRoute: ProfileRoute,
  StreamRoute: StreamRoute,
  TrashRoute: TrashRoute,
  UsersRoute: UsersRoute,
  ApiPublicDebugRoute: ApiPublicDebugRoute,
  ApiPublicDebugInsertRoute: ApiPublicDebugInsertRoute,
  ApiPublicSubmissionsRoute: ApiPublicSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
